services:
  cook:
    image: yunyoujun/cook:1.2.2
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:80"
    tty: true
    labels:  
      createdBy: "Apps"

networks:  
  1panel-network:  
    external: true
