services:
  firefly:
    image: "uusec/firefly:v3.1"
    container_name: ${CONTAINER_NAME}
    restart: always
    devices:
      - /dev/net/tun
    network_mode: host
    volumes:
      - /lib/modules:/lib/modules
      - ./data:/firefly/conf
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - TZ=${TIME_ZONE}
      - FIREFLY_DEVICE=${FIREFLY_DEVICE}
      - FIREFLY_PASSWORD=${FIREFLY_PASSWORD}
      - FIREFLY_AUTO_SSL=${FIREFLY_AUTO_SSL}
      - FIREFLY_PORT=${PANEL_APP_PORT_HTTP}
    labels:  
      createdBy: "Apps"