services:
  chemex:
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    volumes:
      - "${ENV_PATH}:/var/www/html/laravel/.env"
    ports:
      - "${PANEL_APP_PORT_HTTP}:8000"
    environment:
      - "DB_CONNECTION=mysql"
      - "DB_HOST=${PANEL_DB_HOST}"
      - "DB_PORT=${CHEMEX_DB_PORT}"
      - "DB_DATABASE=${PANEL_DB_NAME}"
      - "DB_USERNAME=${PANEL_DB_USER}"
      - "DB_PASSWORD=${PANEL_DB_USER_PASSWORD}"
      - "REDIS_HOST=${PANEL_REDIS_DB_HOST}"
      - "REDIS_PORT=${REDIS_DB_PORT}"
      - "REDIS_PASSWORD=${PANEL_DB_ROOT_PASSWORD}"
    tty: true
    image: celaraze/chemex:latest
    labels:  
      createdBy: "Apps"

networks:  
  1panel-network:  
    external: true

