services:
  xiaoya:
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:80"
    volumes:
      - "./data:/data"
    #environment:
    #  - HTTP_PROXY=${proxy_url}
    #  - HTTPS_PROXY=${proxy_url}
    #  - no_proxy=*.aliyundrive.com
    image: xiaoyaliu/alist:latest
    labels:  
      createdBy: "Apps"

networks:  
  1panel-network:  
    external: true
