services:
  rsshub:
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:1200"
    environment:
      - "NODE_ENV=production"
      - "CACHE_TYPE=redis"
      - "REDIS_URL=redis://:${REDIS_PASS}@${REDIS_HOST}:${REDIS_PORT}"
      - "PUPPETEER_WS_ENDPOINT=ws://rsshub-browserless:3000"
    image: diygod/rsshub:latest
    depends_on:
      - rsshub-browserless
    labels:
      createdBy: Apps

  rsshub-browserless:
    container_name: ${CONTAINER_NAME}-browserless
    restart: always
    networks:
      - 1panel-network
    ulimits:
      core:
        hard: 0
        soft: 0
    image: browserless/chrome:latest
    labels:  
      createdBy: "Apps"

networks:  
  1panel-network:  
    external: true
