services:
  langchain-chatchat:
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:8501"
    deploy:
      resources:
        reservations:
          devices:
            - driver: ${GPU_DRIVER_TYPE}
              count: all
              capabilities: [gpu]
    image: registry.cn-beijing.aliyuncs.com/chatchat/chatchat:0.2.10
    labels:  
      createdBy: "Apps"

networks:  
  1panel-network:  
    external: true
