services:
  linkstack:
    image: linkstackorg/linkstack
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:80"
      - "${PANEL_APP_PORT_HTTPS}:443"
    hostname: ${CONTAINER_NAME}
    environment:
      - HTTP_SERVER_NAME=${HTTP_SERVER_NAME}
      - HTTPS_SERVER_NAME=${HTTPS_SERVER_NAME}
      - SERVER_ADMIN=${SERVER_ADMIN}
      - TZ=${TIME_ZONE}
      - PHP_MEMORY_LIMIT=${PHP_MEMORY_LIMIT}
      - UPLOAD_MAX_FILESIZE=${UPLOAD_MAX_FILESIZE}
    volumes:
      - linkstack:/htdocs
    labels:  
      createdBy: "Apps"

volumes:
  linkstack:

networks:  
  1panel-network:  
    external: true