services:
  streaming-media-server-pro:
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:8080"
    volumes:
      - ./data/assets:/code/app/assets
    image: 239144498/streaming:2023-01-03
    labels:  
      createdBy: "Apps"

networks:  
  1panel-network:  
    external: true
