services:
  smartdns:
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:53/udp"
    volumes:
      - "./data:/etc/smartdns"
    image: pymumu/smartdns:latest
    labels:  
      createdBy: "Apps"

networks:  
  1panel-network:  
    external: true
