services:
  fossbilling:
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:80"
    volumes:
      - fossbilling:/var/www/html
    image: fossbilling/fossbilling:latest
    labels:  
      createdBy: "Apps"

volumes:
  fossbilling:

networks:  
  1panel-network:  
    external: true
