services:
  element-web:
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:80"
    image: vectorim/element-web:latest
    labels:  
      createdBy: "Apps"

networks:  
  1panel-network:  
    external: true
