services:
  emby:
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:8096"
      - "${PANEL_APP_PORT_HTTPS}:8920"
    volumes:
      - "${DATA_PATH}:/config"
      - "${MOUNT_PATH}:/mnt/share1"
      - "${MOUNT_PATH2}:/mnt/share2"
    environment:
      - UID=1000
      - GID=100
      - GIDLIST=100
    #runtime: nvidia # Expose NVIDIA GPUs
    #runtime: nvidia # Expose NVIDIA GPUs
    devices:
      - /dev/dri:/dev/dri # VAAPI/NVDEC/NVENC render nodes
      #- /dev/vchiq:/dev/vchiq # MMAL/OMX on Raspberry Pi
    image: emby/embyserver_arm32v7:latest
    labels:  
      createdBy: "Apps"

networks:  
  1panel-network:  
    external: true
