services:
  iperf:
    image: "networkstatic/iperf3:latest"
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:5201"
    environment:
      - TZ=${TIME_ZONE}
    command: ${IPERF_COMMAND}
    stdin_open: true
    tty: true
    labels:
      createdBy: "Apps"

networks:
  1panel-network:
    external: true
