services:
  nginx-ui:
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:80"
      - "${PANEL_APP_PORT_HTTPS}:443"
    volumes:
      - ${DATA_PATH}/nginx:/etc/nginx
      - ${DATA_PATH}/nginx-ui:/etc/nginx-ui
      - ${WEB_PATH}:/var/www
    environment:
      - TZ=Asia/Shanghai
    image: uozi/nginx-ui:latest
    labels:  
      createdBy: "Apps"

networks:  
  1panel-network:  
    external: true
