services:
  happy-chatgpt:
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:3000"
    environment:
      - "OPENAI_API_KEY=${API_KEY}"
      - "HTTPS_PROXY=${HTTPS_PROXY}"
      - "OPENAI_API_BASE_URL=${API_BASE_URL}"
      - "HEAD_SCRIPTS=${HEAD_SCRIPTS_VAULE}"
      - "PUBLIC_SECRET_KEY=${PUBLIC_SECRET_KEY_VAULE}"
      - "SITE_PASSWORD=${SECRET_KEY}"
      - "OPENAI_API_MODEL=${API_MODEL}"
    image: ddiu8081/chatgpt-demo:latest
    labels:  
      createdBy: "Apps"

networks:  
  1panel-network:  
    external: true
