services:
  homepage:
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:3000"
    volumes:
      - ./data/config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - PUID=1000
      - PGID=1000
    image: ghcr.io/gethomepage/homepage:latest
    labels:  
      createdBy: "Apps"

networks:  
  1panel-network:  
    external: true
