services:
  rss-reader:
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:8080"
    volumes:
      - "${DATA_PATH}/db:/app/db"
      - "./data/config.json:/app/config.json"
    image: srcrs/rss-reader:v2.1
    labels:  
      createdBy: "Apps"

networks:  
  1panel-network:  
    external: true
