services:
  picx:
    build:
      context: .
      dockerfile: Dockerfile
    image: picx:latest
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:80"
    volumes:
      - ${DATA_PATH}:/usr/share/nginx/html
    labels:  
      createdBy: "Apps" 

networks:  
  1panel-network:  
    external: true
