services:
  it-tools:
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:80"
    image: corentinth/it-tools:latest
    labels:  
      createdBy: "Apps"

networks:  
  1panel-network:  
    external: true
