services:
  kkfileview:
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:8012"
    image: keking/kkfileview:4.1.0
    labels:  
      createdBy: "Apps"

networks:  
  1panel-network:  
    external: true
