services:
  dashy:
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:8080"
    volumes:
      - ./data/user-data/conf.yml:/app/user-data/conf.yml
      - ./data/item-icons:/app/user-data/item-icons
    environment:
      - NODE_ENV=production
      - UID=1000
      - GID=1000
    healthcheck:
     test: ['CMD', 'node', '/app/services/healthcheck']
     interval: 1m30s
     timeout: 10s
     retries: 3
     start_period: 40s
    image: lissy93/dashy:latest
    labels:  
      createdBy: "Apps"

networks:  
  1panel-network:  
    external: true
