services:
  gowebdav:
    image: 117503445/go_webdav:latest
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:80"
    environment:
      - "dav=${DAV}"
    volumes:
      - ${DATA_PATH}:${INNER_DATA_PATH}
      - ${DATA_PATH2}:${INNER_DATA_PATH2}
    labels:  
      createdBy: "Apps"

networks:  
  1panel-network:  
    external: true
