services:
  headscale-ui:
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTPS}:443"
    image: ghcr.io/gurucomputing/headscale-ui:latest
    labels:  
      createdBy: "Apps"

networks:  
  1panel-network:  
    external: true
