services:
  onenav:
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:80"
    volumes:
      - "${DATA_PATH}:/data/wwwroot/default/data"
    image: helloz/onenav:0.9.35
    labels:  
      createdBy: "Apps"

networks:  
  1panel-network:  
    external: true
