services:
  dbgate:
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
        - "${PANEL_APP_PORT_HTTP}:3000"
    volumes:
        - "${DATA_PATH}:/root/.dbgate"
    image: "dbgate/dbgate:5.3.1"
    labels:  
      createdBy: "Apps"

networks:  
  1panel-network:  
    external: true