services:
  cookiecloud:
    image: easychen/cookiecloud:latest
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:8088"
    volumes:
      - "${DATA_PATH}:/data/api/data"
    environment:
      - API_ROOT=${API_ROOT}
    labels:  
      createdBy: "Apps"

networks:  
  1panel-network:  
    external: true
