services:
  mcsm-web:
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:23333"
    volumes:
      - "${DATA_PATH}:/opt/mcsmanager/web/data"
    image: alisaqaq/mcsmanager-web:10.1.0
    labels:  
      createdBy: "Apps"

networks:  
  1panel-network:  
    external: true
