services:
  sub-store:
    image: xream/sub-store:latest
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:3001"
    environment:
      - SUB_STORE_PUSH_SERVICE=${SUB_STORE_PUSH_SERVICE}
      - SUB_STORE_CRON=${SUB_STORE_CRON}
      - SUB_STORE_FRONTEND_BACKEND_PATH=${SUB_STORE_FRONTEND_BACKEND_PATH}
    volumes:
      - ${DATA_PATH}:/opt/app/data
    labels:  
      createdBy: "Apps"

networks:  
  1panel-network:  
    external: true