services:
  easyimage:
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:80"
    volumes:
      - "${DATA_PATH}/config:/app/web/config"
      - "${DATA_PATH}/i:/app/web/i"
    environment:
      - TZ=Asia/Shanghai
      - PUID=1000
      - PGID=1000
      - DEBUG=false
    image: ddsderek/easyimage:v2.8.3-r1
    labels:  
      createdBy: "Apps"

networks:  
  1panel-network:  
    external: true
