services:
  resilio-sync:
    image: linuxserver/resilio-sync:latest
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:8888"
      - "${PANEL_APP_PORT_SYNC}:55555"
    volumes:
      - ${CONFIG_PATH}:/config
      - ${DOWNLOADS_PATH}:/downloads
      - ${SYNC_PATH}:/sync
      - ${EXTERNAL_MOUNT_PATH}:${INTERNAL_MOUNT_PATH}
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - TZ=${TIME_ZONE}
    labels:
      createdBy: "Apps"

networks:
  1panel-network:
    external: true
