services:
  trilium:
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:8080"
    volumes:
      - "${DATA_PATH}:/home/node/trilium-data"
    tty: true
    image: zadam/trilium:0.63.7
    labels:  
      createdBy: "Apps"

networks:  
  1panel-network:  
    external: true
