services:
  chuanhuchat:
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:7860"
    volumes:
      - ./data/history:/app/history
      - ./data/config.json:/app/config.json
    image: tuchuanhuhuhu/chuanhuchatgpt:latest
    labels:  
      createdBy: "Apps"

networks:  
  1panel-network:  
    external: true
