services:
  chatgpt-on-wechat:
    image: "zhayujie/chatgpt-on-wechat:latest"
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    security_opt:
      - seccomp:unconfined
    environment:
      - OPEN_AI_API_KEY=${OPEN_AI_API_KEY}
      - OPEN_AI_API_BASE=${OPEN_AI_API_BASE}
      - MODEL=${MODEL}
      - USE_AZURE_CHATGPT=${USE_AZURE_CHATGPT}
      - AZURE_DEPLOYMENT_ID=${AZURE_DEPLOYMENT_ID}
      - AZURE_API_VERSION=${AZURE_API_VERSION}
      - PROXY=${PROXY}
      - SINGLE_CHAT_PREFIX=${SINGLE_CHAT_PREFIX}
      - SINGLE_CHAT_REPLY_PREFIX=${SINGLE_CHAT_REPLY_PREFIX}
      - SINGLE_CHAT_REPLY_SUFFIX=${SINGLE_CHAT_REPLY_SUFFIX}
      - GROUP_CHAT_PREFIX=${GROUP_CHAT_PREFIX}
      - GROUP_CHAT_REPLY_PREFIX=${GROUP_CHAT_REPLY_PREFIX}
      - GROUP_CHAT_REPLY_SUFFIX=${GROUP_CHAT_REPLY_SUFFIX}
      - GROUP_CHAT_KEYWORD=${GROUP_CHAT_KEYWORD}
      - GROUP_AT_OFF=${GROUP_AT_OFF}
      - GROUP_NAME_WHITE_LIST=${GROUP_NAME_WHITE_LIST}
      - GROUP_NAME_KEYWORD_WHITE_LIST=${GROUP_NAME_KEYWORD_WHITE_LIST}
      - GROUP_CHAT_IN_ONE_SESSION=${GROUP_CHAT_IN_ONE_SESSION}
      - NICK_NAME_BLACK_LIST=${NICK_NAME_BLACK_LIST}
      - GROUP_WELCOME_MSG=${GROUP_WELCOME_MSG}
      - TRIGGER_BY_SELF=${TRIGGER_BY_SELF}
      - TEXT_TO_IMAGE=${TEXT_TO_IMAGE}
      - DALLE3_IMAGE_STYLE=${DALLE3_IMAGE_STYLE}
      - DALLE3_IMAGE_QUALITY=${DALLE3_IMAGE_QUALITY}
      - AZURE_OPENAI_DALLE_API_BASE=${AZURE_OPENAI_DALLE_API_BASE}
      - AZURE_OPENAI_DALLE_API_KEY=${AZURE_OPENAI_DALLE_API_KEY}
      - AZURE_OPENAI_DALLE_DEPLOYMENT_ID=${AZURE_OPENAI_DALLE_DEPLOYMENT_ID}
      - IMAGE_PROXY=${IMAGE_PROXY}
      - IMAGE_CREATE_PREFIX=${IMAGE_CREATE_PREFIX}
      - CONCURRENCY_IN_SESSION=${CONCURRENCY_IN_SESSION}
      - IMAGE_CREATE_SIZE=${IMAGE_CREATE_SIZE}
      - GROUP_CHAT_EXIT_GROUP=${GROUP_CHAT_EXIT_GROUP}
      - EXPIRES_IN_SECONDS=${EXPIRES_IN_SECONDS}
      - CHARACTER_DESC=${CHARACTER_DESC}
      - CONVERSATION_MAX_TOKENS=${CONVERSATION_MAX_TOKENS}
      - RATE_LIMIT_CHATGPT=${RATE_LIMIT_CHATGPT}
      - RATE_LIMIT_DALLE=${RATE_LIMIT_DALLE}
      - TEMPERATURE=${TEMPERATURE}
      - TOP_P=${TOP_P}
      - FREQUENCY_PENALTY=${FREQUENCY_PENALTY}
      - PRESENCE_PENALTY=${PRESENCE_PENALTY}
      - REQUEST_TIMEOUT=${REQUEST_TIMEOUT}
      - TIMEOUT=${TIMEOUT}
      - BAIDU_WENXIN_MODEL=${BAIDU_WENXIN_MODEL}
      - BAIDU_WENXIN_API_KEY=${BAIDU_WENXIN_API_KEY}
      - BAIDU_WENXIN_SECRET_KEY=${BAIDU_WENXIN_SECRET_KEY}
      - XUNFEI_APP_ID=${XUNFEI_APP_ID}
      - XUNFEI_API_KEY=${XUNFEI_API_KEY}
      - XUNFEI_API_SECRET=${XUNFEI_API_SECRET}
      - CLAUDE_API_COOKIE=${CLAUDE_API_COOKIE}
      - CLAUDE_UUID=${CLAUDE_UUID}
      - CLAUDE_API_KEY=${CLAUDE_API_KEY}
      - QWEN_ACCESS_KEY_ID=${QWEN_ACCESS_KEY_ID}
      - QWEN_ACCESS_KEY_SECRET=${QWEN_ACCESS_KEY_SECRET}
      - QWEN_AGENT_KEY=${QWEN_AGENT_KEY}
      - QWEN_APP_ID=${QWEN_APP_ID}
      - QWEN_NODE_ID=${QWEN_NODE_ID}
      - DASHSCOPE_API_KEY=${DASHSCOPE_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - WEWORK_SMART=${WEWORK_SMART}
      - SPEECH_RECOGNITION=${SPEECH_RECOGNITION}
      - GROUP_SPEECH_RECOGNITION=${GROUP_SPEECH_RECOGNITION}
      - VOICE_REPLY_VOICE=${VOICE_REPLY_VOICE}
      - ALWAYS_REPLY_VOICE=${ALWAYS_REPLY_VOICE}
      - VOICE_TO_TEXT=${VOICE_TO_TEXT}
      - TEXT_TO_VOICE=${TEXT_TO_VOICE}
      - TEXT_TO_VOICE_MODEL=${TEXT_TO_VOICE_MODEL}
      - TTS_VOICE_ID=${TTS_VOICE_ID}
      - BAIDU_APP_ID=${BAIDU_APP_ID}
      - BAIDU_API_KEY=${BAIDU_API_KEY}
      - BAIDU_SECRET_KEY=${BAIDU_SECRET_KEY}
      - BAIDU_DEV_PID=${BAIDU_DEV_PID}
      - AZURE_VOICE_API_KEY=${AZURE_VOICE_API_KEY}
      - AZURE_VOICE_REGION=${AZURE_VOICE_REGION}
      - XI_API_KEY=${XI_API_KEY}
      - XI_VOICE_ID=${XI_VOICE_ID}
      - CHAT_TIME_MODULE=${CHAT_TIME_MODULE}
      - CHAT_START_TIME=${CHAT_START_TIME}
      - CHAT_STOP_TIME=${CHAT_STOP_TIME}
      - TRANSLATE=${TRANSLATE}
      - BAIDU_TRANSLATE_APP_ID=${BAIDU_TRANSLATE_APP_ID}
      - BAIDU_TRANSLATE_APP_KEY=${BAIDU_TRANSLATE_APP_KEY}
      - HOT_RELOAD=${HOT_RELOAD}
      - WECHATY_PUPPET_SERVICE_TOKEN=${WECHATY_PUPPET_SERVICE_TOKEN}
      - WECHATMP_TOKEN=${WECHATMP_TOKEN}
      - WECHATMP_PORT=${WECHATMP_PORT}
      - WECHATMP_APP_ID=${WECHATMP_APP_ID}
      - WECHATMP_APP_SECRET=${WECHATMP_APP_SECRET}
      - WECHATMP_AES_KEY=${WECHATMP_AES_KEY}
      - WECHATCOM_CORP_ID=${WECHATCOM_CORP_ID}
      - WECHATCOMAPP_TOKEN=${WECHATCOMAPP_TOKEN}
      - WECHATCOMAPP_PORT=${WECHATCOMAPP_PORT}
      - WECHATCOMAPP_SECRET=${WECHATCOMAPP_SECRET}
      - WECHATCOMAPP_AGENT_ID=${WECHATCOMAPP_AGENT_ID}
      - WECHATCOMAPP_AES_KEY=${WECHATCOMAPP_AES_KEY}
      - FEISHU_PORT=${FEISHU_PORT}
      - FEISHU_APP_ID=${FEISHU_APP_ID}
      - FEISHU_APP_SECRET=${FEISHU_APP_SECRET}
      - FEISHU_TOKEN=${FEISHU_TOKEN}
      - FEISHU_BOT_NAME=${FEISHU_BOT_NAME}
      - DINGTALK_CLIENT_ID=${DINGTALK_CLIENT_ID}
      - DINGTALK_CLIENT_SECRET=${DINGTALK_CLIENT_SECRET}
      - DINGTALK_CARD_ENABLED=${DINGTALK_CARD_ENABLED}
      - CLEAR_MEMORY_COMMANDS=${CLEAR_MEMORY_COMMANDS}
      - CHANNEL_TYPE=${CHANNEL_TYPE}
      - SUBSCRIBE_MSG=${SUBSCRIBE_MSG}
      - DEBUG=${DEBUG}
      - APPDATA_DIR=${APPDATA_DIR}
      - PLUGIN_TRIGGER_PREFIX=${PLUGIN_TRIGGER_PREFIX}
      - USE_GLOBAL_PLUGIN_CONFIG=${USE_GLOBAL_PLUGIN_CONFIG}
      - MAX_MEDIA_SEND_COUNT=${MAX_MEDIA_SEND_COUNT}
      - MEDIA_SEND_INTERVAL=${MEDIA_SEND_INTERVAL}
      - ZHIPU_AI_API_KEY=${ZHIPU_AI_API_KEY}
      - ZHIPU_AI_API_BASE=${ZHIPU_AI_API_BASE}
      - MOONSHOT_API_KEY=${MOONSHOT_API_KEY}
      - MOONSHOT_BASE_URL=${MOONSHOT_BASE_URL}
      - USE_LINKAI=${USE_LINKAI}
      - LINKAI_API_KEY=${LINKAI_API_KEY}
      - LINKAI_APP_CODE=${LINKAI_APP_CODE}
      - LINKAI_API_BASE=${LINKAI_API_BASE}
    labels:  
      createdBy: "Apps"

networks:  
  1panel-network:  
    external: true
