services:
  obsidian-zh:
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:6090"
      - "${PANEL_APP_PORT_VNC}:5900"
      - "${PANEL_APP_PORT_SSH}:22"
    volumes:
      - ${DATA_PATH}/vaults:/vaults
    environment:
      - PASSWD=${HTTP_PWD}
      - SIZE=${DISPLAY_SIZE}
    privileged: ${PRIVILEGED_MODE}
    image: hcyxsmile/obsidian-docker:v1.0-ob1.3.5
    labels:  
      createdBy: "Apps"

networks:  
  1panel-network:  
    external: true
