services:
  meowfacts:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        IMAGE_TAG: latest
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:5000"
    labels:  
      createdBy: "Apps" 

networks:  
  1panel-network:  
    external: true

