services:
  watchtower:
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=Asia/Shanghai
      - ${ENV1}
    command: ${COMMAND1}
    image: containrrr/watchtower:1.7.1
    labels:
      createdBy: "Apps"

networks:
  1panel-network:
    external: true
