services:
  softether:
    image: "softethervpn/vpnserver:latest"
    cap_add:
      - NET_ADMIN
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - ${VPN_PORT_53}:53
      - ${VPN_PORT_443}:443
      - ${VPN_PORT_992}:992
      - ${VPN_PORT_1194_UDP}:1194/udp
      - ${VPN_PORT_5555}:5555
      - ${VPN_PORT_500_UDP}:500/udp
      - ${VPN_PORT_4500_UDP}:4500/udp
      - ${VPN_PORT_1701_UDP}:1701/udp
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - ${SOFTETHER_DATA_PATH}:/mnt
      - ${SOFTETHER_LOG_PATH}:/root/server_log
      - ${SOFTETHER_PACKETLOG_PATH}:/root/packet_log
      - ${SOFTETHER_SECURITYLOG_PATH}:/root/security_log
    labels:
      createdBy: "Apps"
networks:
  1panel-network:
    external: true