services:
  speedtest:
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - ${PANEL_APP_PORT_HTTP}:3000
      - ${PANEL_APP_PORT_HTTPS}:3001
    image: openspeedtest/latest:latest
    labels:  
      createdBy: "Apps"

networks:  
  1panel-network:  
    external: true