services:
  moments:
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:80"
    volumes:
      - "moments_data:/app"
    image: drizzle2001/moments:latest
    labels:  
      createdBy: "Apps"

volumes:
  moments_data:

networks:  
  1panel-network:  
    external: true
