services:
  xunlei:
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:${PANEL_APP_PORT_HTTP}"
    volumes:
      - "${DATA_PATH}:/xunlei/data"
      - "${DOWNLOAD_PATH}:/xunlei/downloads"
    environment:
      - UID=1000
      - GID=1000
      - XL_DEBUG=0
      - XL_WEB_PORT=${PANEL_APP_PORT_HTTP}
      - XL_BA_USER=${HTTP_USER}
      - XL_BA_PASSWORD=${HTTP_PWD}
    hostname: ${HOSTNAME}
    privileged: true
    image: cnk3x/xunlei:latest
    labels:  
      createdBy: "Apps"

networks:  
  1panel-network:  
    external: true
