services:
  nginxpm:
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:80"
      - "${PANEL_APP_PORT_HTTP1}:81"
      - "${PANEL_APP_PORT_HTTP2}:443"
    volumes:
      - "${DATA_PATH}:/data"
      - "${SSL_PATH}:/etc/letsencrypt"
    image: chishin/nginx-proxy-manager-zh:release
    labels:  
      createdBy: "Apps"

networks:  
  1panel-network:  
    external: true
