services:
  aliyundrive-webdav:
    image: "messense/aliyundrive-webdav:main"
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:8080"
    volumes:
      - ${DATA_PATH}:/etc/aliyundrive-webdav/
    environment:
      - REFRESH_TOKEN=${REFRESH_TOKEN}
      - WEBDAV_AUTH_USER=${WEBDAV_AUTH_USER}
      - WEBDAV_AUTH_PASSWORD=${WEBDAV_AUTH_PASSWORD}
    labels:
      createdBy: "Apps"

networks:  
  1panel-network:  
    external: true