services:
  surveyking:
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:1991"
    volumes:
      - "${DATA_PATH}/files:/surveyking/files"
      - "${DATA_PATH}/logs:/surveyking/logs"
    image: surveyking/surveyking:latest
    labels:  
      createdBy: "Apps"

networks:  
  1panel-network:  
    external: true
