services:
  amprobe:
    image: amuluze/amprobe:v1.3.3
    container_name: ${CONTAINER_NAME}
    restart: always
    network_mode: "host"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /dev:/host/dev:ro
      - ./data/configs:/app/configs
      - ./data/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./data/supervisor:/etc/supervisor/conf.d
    labels:  
      createdBy: "Apps"
