services:
  web-check:
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:3000"
    image: lissy93/web-check:latest
    labels:  
      createdBy: "Apps"

networks:  
  1panel-network:  
    external: true

