services:
  headscale:
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      1panel-network:
        ipv4_address: ${SUBNET}
    ports:
      - "${PANEL_APP_PORT_HTTP}:8080"
    volumes:
      - "./data/config:/etc/headscale"
      - "./data/data:/var/lib/headscale"
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv6.conf.all.forwarding=1
    command: ['headscale', 'serve']
    image: headscale/headscale:0.23.0
    labels:  
      createdBy: "Apps"

networks:  
  1panel-network:  
    external: true
