services:
  hexo:
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:4000"
    volumes:
      - hexo_data:/home/hexo/.hexo
    image: taskbjorn/hexo:alpine-latest
    labels:  
      createdBy: "Apps"

volumes:
  hexo_data:

networks:  
  1panel-network:  
    external: true
