services:
  pic-smaller:
    image: "vimiix/pic-smaller:20240517"
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
        - "${PANEL_APP_PORT_HTTP}:3000"
    labels:  
      createdBy: "Apps"
   
networks:  
  1panel-network:  
    external: true