services:
  port-forward-server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        IMAGE_TAG: 1.3.7
    container_name: ${CONTAINER_NAME}
    restart: always
    network_mode: host
    volumes:
      - "./data:/app/pfg/forward-agent/conf"
    cap_add:
      - NET_ADMIN
    labels:  
      createdBy: "Apps" 
