services:
  van-nav:
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:6412"
    volumes:
      - "${DATA_PATH}:/app/data"
    image: mereith/van-nav:latest
    labels:  
      createdBy: "Apps"

networks:  
  1panel-network:  
    external: true

