services:
  hasty-paste:
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:8000"
    volumes:
      - hpaste_data:/app/data
    environment:
      - TZ=Asia/Shanghai
    image: ghcr.io/enchant97/hasty-paste:latest
    labels:  
      createdBy: "Apps"

volumes:
  hpaste_data:

networks:  
  1panel-network:  
    external: true
