services:
  modstartblog:
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:80"
    volumes:
      - ./data:/server/web
    image: modstart/modstartblog:v8.6.0
    labels:
      createdBy: "Apps"

networks:
  1panel-network:
    external: true
