services:
  frp-panel-master:
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:9000"
      - "${PANEL_APP_PORT_RPC}:9001"
    volumes:
      - "${DATA_PATH}:/data"
    environment:
      - APP_GLOBAL_SECRET=${APP_GLOBAL_SECRET}
      - MASTER_RPC_HOST=${MASTER_RPC_HOST}
    image: vaalacat/frp-panel:latest
    labels:  
      createdBy: "Apps"

networks:  
  1panel-network:  
    external: true
