services:
  obsidian:
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:${PANEL_APP_PORT_HTTP}"
      - "${PANEL_APP_PORT_HTTPS}:${PANEL_APP_PORT_HTTPS}"
    volumes:
      - ${DATA_PATH}/vaults:/vaults
      - ${DATA_PATH}/config:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIME_ZONE}
      - DOCKER_MODS=linuxserver/mods:universal-git
      - CUSTOM_PORT=${PANEL_APP_PORT_HTTP}
      - CUSTOM_HTTPS_PORT=${PANEL_APP_PORT_HTTPS}
      - CUSTOM_USER=${HTTP_USER}
      - PASSWORD=${HTTP_PWD}
    image: sytone/obsidian-remote:arm64
    labels:  
      createdBy: "Apps"

networks:  
  1panel-network:  
    external: true
