services:
  sublink:
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:5000"
    volumes:
      - sublink_data:/app/app/db
    image: jaaksi/sublink:latest
    labels:  
      createdBy: "Apps"

volumes:
  sublink_data:
    name: sublink_data

networks:  
  1panel-network:  
    external: true
