services:
  alist-encrypt:
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:5344"
    volumes:
      - "${DATA_PATH}:/node-proxy/conf"
    environment:
      - TZ=${TIME_ZONE}
      - ALIST_HOST=${ALIST_HOST}
    image: prophet310/alist-encrypt:beta
    labels:  
      createdBy: "Apps"

networks:  
  1panel-network:  
    external: true
