services:
  samba:
    image: "elswork/samba:4.18.9"
    container_name: ${CONTAINER_NAME}
    hostname: ${HOSTNAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:139"
      - "${PANEL_APP_PORT_SMB}:445"
    environment:
      - TZ=${TZ}
    volumes:
      - "${DATA_PATH}:${INTERNAL_DATA_PATH}"
    command:
      -u "${USER_1}"
      -s "${SHARE_1}"
      #-u "${USER_2}"
      #-s "${SHARE_2}"
      #-u "${USER_3}"
      #-s "${SHARE_3}"
      
    labels:
      createdBy: "Apps"

networks:
  1panel-network:
    external: true
