services:
  syncclipboard-server:
    image: jericx/syncclipboard-server:latest
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:5033"
    volumes:
      - ${CONFIG_FILE_PATH}:/app/appsettings.json
    labels:  
      createdBy: "Apps"

networks:  
  1panel-network:  
    external: true
