services:
  litespeed:
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    logging:
      driver: none
    volumes:
      - ${DATA_PATH}/lsws/conf:/usr/local/lsws/conf
      - ${DATA_PATH}/lsws/admin-conf:/usr/local/lsws/admin/conf
      - ${DATA_PATH}/bin/container:/usr/local/bin
      - ${DATA_PATH}/sites:/var/www/vhosts/
      - ${DATA_PATH}/acme:/root/.acme.sh/
      - ${DATA_PATH}/logs:/usr/local/lsws/logs/
    ports:
      - "${PANEL_APP_PORT_HTTP}:80"
      - "${PANEL_APP_PORT_HTTPS}:443"
      - "${PANEL_APP_PORT_HTTPS}:443/udp"
      - "${PANEL_APP_PORT_CONSOLE}:7080"
    environment:
      - TZ=${TIME_ZONE}
    image: litespeedtech/openlitespeed:1.8.1-lsphp74
    labels:  
      createdBy: "Apps"

networks:  
  1panel-network:  
    external: true
