services:
  picimpact:
    image: besscroft/picimpact:latest
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:3000"
    environment:
      - DATABASE_URL=postgres://${PANEL_DB_USER}:${PANEL_DB_USER_PASSWORD}@${PANEL_DB_HOST}:${PANEL_DB_PORT}/${PANEL_DB_NAME}
      - AUTH_SECRET=${AUTH_SECRET}
    labels:
      createdBy: "Apps"

networks:
  1panel-network:
    external: true
