services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:8080"
    environment:
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - "${DATA_PATH}:/app/backend/data"
    labels:  
      createdBy: "Apps"

networks:  
  1panel-network:  
    external: true
