services:
  stackedit:
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:8080"
    volumes:
      - "${DATA_PATH}:/data"
    image: benweet/stackedit:v5.15.4
    labels:  
      createdBy: "Apps"

networks:  
  1panel-network:  
    external: true
