services:
  dashmachine:
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:5000"
    volumes:
      - "${DATA_PATH}:/dashmachine/dashmachine/user_data"
    image: rmountjoy/dashmachine:latest
    labels:  
      createdBy: "Apps"

networks:  
  1panel-network:  
    external: true
