services:
  npc:
    image: yisier1/npc:latest
    restart: always
    network_mode: "host"
    command: -server=${NPS_SERVER_ADDR} -vkey=${NPS_VKEY} -tls_enable=${TLS_ENABLE_SWITCH}
    container_name: ${CONTAINER_NAME}
    labels:
      createdBy: "Apps"
