services:
  mynodequery:
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:5000"
    volumes:
      - ./data/appsettings.json:/app/appsettings.json
    logging:
      options:
        max-size: 256MB
    image: jaydenlee2019/mynodequery:1.0.5.1
    labels:  
      createdBy: "Apps"

networks:  
  1panel-network:  
    external: true
