services:
  spider-admin-pro:
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:8000"
    image: mouday/spider-admin-pro:latest
    labels:  
      createdBy: "Apps"

networks:  
  1panel-network:  
    external: true
