services:
  remmina:
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:3000"
      - "${PANEL_APP_PORT_HTTPS}:3001"
    volumes:
      - "${DATA_PATH}:/config"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIME_ZONE}
      - CUSTOM_USER=${HTTP_USER}
      - PASSWORD=${HTTP_PWD}
    image: linuxserver/remmina:1.4.2
    labels:  
      createdBy: "Apps"

networks:  
  1panel-network:  
    external: true
